In [80]:
import json as json
import pathlib as pl
from copy import deepcopy
from datetime import datetime
from gc import collect
from os import path, system
from warnings import simplefilter

import matplotlib.pyplot as plt
from matplotlib import rcParams
from numpy import array, linspace, meshgrid, ones, zeros, set_printoptions
from numpy.linalg import norm
from scipy.spatial.transform import Rotation
from tqdm import tqdm
from pandas import read_csv

from pympc.models.catenary import Catenary
from pympc.models.seafloor import SeafloorFromFunction
from pympc.utils import check, compare_dict, gif_from_pngs, print_dict

simplefilter( 'ignore', RuntimeWarning )

gain = 1.5
rcParams[ 'figure.figsize' ] = [ gain * 6.4, gain * 4.8 / 2 ]
set_printoptions( precision=2, linewidth=10000, suppress=True )
# rcParams['figure.facecolor'] = 'black'
# rcParams['axes.edgecolor'] = 'white'
# rcParams['axes.facecolor'] = 'black'
# rcParams['axes.labelcolor'] = 'white'
# rcParams['xtick.color'] = 'white'
# rcParams['ytick.color'] = 'white'
# rcParams['legend.labelcolor'] = 'white'
# rcParams['legend.facecolor'] = 'black'

In [81]:
files = list( pl.Path( "./export" ).glob( '*' ) )
files.sort( key=lambda x: path.getctime( x ) )
for v in files:
    print( str( v ).split( '//' )[ -1 ], end='\t' )
    print( datetime.fromtimestamp( path.getctime( v ) ) )

export\three_robots_chain_1726157070	2025-01-22 17:06:29.134157
export\three_robots_chain_1726514783	2025-01-22 17:06:29.162731
export\three_robots_chain_with_fixed_end_1726429003	2025-01-22 17:06:29.173252
export\three_robots_chain_with_fixed_end_1726554218	2025-01-22 17:06:29.185844
export\1732024220.csv	2025-01-22 17:27:45.720932
export\config.json	2025-01-22 17:27:45.749478
export\Figure_1.png	2025-01-22 17:27:47.085018
export\pretty_config.json	2025-01-22 17:27:47.090524
export\chain_of_four_1730371997	2025-01-22 17:27:47.093531
export\chain_of_four_1730384599	2025-01-22 17:32:37.135312
export\chain_of_four_1731930190	2025-01-22 17:37:18.872407
export\chain_of_four_1732006722	2025-01-22 17:42:19.389571
export\mpc_simulation_1732024220	2025-01-22 17:46:58.991878
export\__init__.py	2025-05-16 14:42:40.190579
export\mpc_simulation_1747405503	2025-05-16 16:25:03.173407
export\mpc_simulation_1747405611	2025-05-16 16:26:51.323311
export\mpc_simulation_1747405937	2025-05-16 16:32:17.1097

In [82]:
compare_folder_0 = pl.Path( './export/mpc_simulation_1732024220' )
compare_folder_1 = pl.Path( './export/mpc_simulation_1747406167' )
with open( compare_folder_0 / 'config.json' ) as f0:
    with open( compare_folder_1 / 'config.json' ) as f1:
        compare_config_0 = json.load( f0 )
        compare_config_1 = json.load( f1 )
        print( '\t', compare_folder_0, '\t', compare_folder_1, flush=True )
        compare_dict( compare_config_0, compare_config_1 )

	 export\mpc_simulation_1732024220 	 export\mpc_simulation_1747406167
predict <class 'str'> : 	def _pred     def _p
candidate_actuations <class 'list'> : [] []
predicted_trajectories <class 'list'> : [] []
actuation_weight_matrix <class 'list'> : 0 5
os <class 'str'> : Windows Windows
pose_weight_matrix <class 'list'> : 5 5
record <class 'bool'> : True True
time_step <class 'float'> : 0.1 0.1
objective_weight <class 'float'> : 0.01 0.01
os_version <class 'str'> : 10.0.22631 10.0.26100
get_actuation <class 'str'> : 	def _get_     def _g
get_result <class 'str'> : 	def _get_ 
actuation_derivative_weight_matrix <class 'list'> : 5 0
compute_times <class 'list'> : [] []
max_number_of_iteration <class 'int'> : 100 100
horizon <class 'int'> : 5 5
objective <class 'str'> : def chain_ def chain_
tolerance <class 'float'> : 1e-06 1e-06
verbose <class 'bool'> : False False
raw_result <class 'dict'> :
	x <class 'list'> : 1 1
cpu <class 'dict'> :
	hz_actual_friendly <class 'str'> : 1.8000 GHz 3.800

In [83]:
print( array( compare_config_0[ 'pose_weight_matrix' ] )[ 0 ] )

[[10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 

In [84]:
folder = pl.Path( './export/mpc_simulation_1747406167' )
uuid = str( folder ).split( '_' )[ -1 ]
with open( folder / 'config.json' ) as f:
    config = json.load( f )
print_dict( config )

predict <class 'str'> :     def _p ...
get_actuation <class 'str'> :     def _g ...
compute_result <class 'str'> :     def _c ...
model <class 'dict'> :
	dynamics <class 'dict'> :
		compute_error <class 'str'> :     def co ...
		state_size <class 'NoneType'> : None
		actuation_size <class 'NoneType'> : None
		position <class 'NoneType'> : None
		orientation <class 'NoneType'> : None
		velocity <class 'NoneType'> : None
		body_rates <class 'NoneType'> : None
		linear_actuation <class 'NoneType'> : None
		angular_actuation <class 'NoneType'> : None
		br_0 <class 'dict'> :
			compute_error <class 'str'> :     def co ...
			state_size <class 'NoneType'> : None
			actuation_size <class 'NoneType'> : None
			position <class 'NoneType'> : None
			orientation <class 'NoneType'> : None
			velocity <class 'NoneType'> : None
			body_rates <class 'NoneType'> : None
			linear_actuation <class 'NoneType'> : None
			angular_actuation <class 'NoneType'> : None
			REFERENCE_FRAME <class 'list'> : ['NED

In [85]:
slice_repository = { }
axes = [ 'x', 'y', 'z', 'phi', 'theta', 'psi', 'u', 'v', 'w', 'p', 'q', 'r' ]

for k, v in config[ 'model' ][ 'dynamics' ].items():
    if isinstance( v, str ) and '\n' not in v and ':' in v:
        slice_repository[ k ] = slice( *[ int( v ) if v != 'None' else None for v in v.split( ':' ) ] )
    elif isinstance( v, int ) and 'br_' in k:
        slice_repository[ k ] = v
    elif isinstance( v, list ):
        slice_repository[ k ] = array( v )

pose = { k: v for k, v in slice_repository.items() if 'pose' in k }
positions = { k: v for k, v in slice_repository.items() if 'br' in k and 'position' in k }
orientations = { k: v for k, v in slice_repository.items() if 'br' in k and 'orientation' in k }
positions_pairs = { '_'.join( a.split( '_' )[ 1:3 ] ): '_'.join( b.split( '_' )[ 1:3 ] ) for a, b in
                    zip( list( positions )[ :-1 ], list( positions )[ 1: ] ) }
speeds = { k: v for k, v in slice_repository.items() if 'br' in k and 'velocity' in k }
linear_actuation = { k: v for k, v in slice_repository.items() if 'br' in k and 'linear_actuation' in k }
angular_actuation = { k: v for k, v in slice_repository.items() if 'br' in k and 'angular_actuation' in k }

times = [ config[ 'model' ][ 'time_step' ] * i for i in range( len( config[ 'target_trajectory' ] ) ) ]

target_trajectory = array( config[ 'target_trajectory' ] )[ :, 0 ]

pose_weight = array( config[ 'pose_weight_matrix' ][ 0 ] )

save_rate = config.get( 'save_rate', 1 )

seafloor_config = config[ 'model' ][ 'dynamics' ][ 'sf' ]
if seafloor_config[ 'instance_of' ] == 'SeafloorFromFunction':
    exec( seafloor_config[ 'seafloor_function' ] )
    seafloor = SeafloorFromFunction(
            globals()[ seafloor_config[ 'seafloor_function' ].split( '\n' )[ 0 ][ 4: ].split( '(' )[ 0 ] ]
    )
else:
    raise NotImplementedError

In [86]:
for i, c in enumerate( config[ 'constraints' ] ):
    c = c.get( 'constraint', c )
    for j, (lb, ub, label, vlabel) in enumerate( zip( c[ 'lb' ], c[ 'ub' ], c[ 'labels' ], c[ 'value_labels' ] ) ):
        print( f'{(i + 1) * j}.\t{label}: {lb}\t<=\t{vlabel}\t<=\t{ub}' )

0.	seafloor: 0.2	<=	c_01_distance_to_seafloor	<=	inf
1.	seafloor: 0.2	<=	c_12_distance_to_seafloor	<=	inf
2.	seafloor: 0.2	<=	c_23_distance_to_seafloor	<=	inf
3.	seafloor: 0.2	<=	br_0_distance_to_seafloor	<=	inf
4.	seafloor: 0.2	<=	br_1_distance_to_seafloor	<=	inf
5.	seafloor: 0.2	<=	br_2_distance_to_seafloor	<=	inf
6.	seafloor: 0.2	<=	br_3_distance_to_seafloor	<=	inf
7.	cable_length: 0.2	<=	br_0_br_1_horizontal_distance	<=	2.8
8.	cable_length: 0.2	<=	br_1_br_2_horizontal_distance	<=	2.8
9.	cable_length: 0.2	<=	br_2_br_3_horizontal_distance	<=	2.8
10.	cable_length: -inf	<=	br_0_br_1_distance	<=	2.8
11.	cable_length: -inf	<=	br_1_br_2_distance	<=	2.8
12.	cable_length: -inf	<=	br_2_br_3_distance	<=	2.8


In [87]:
data_files = [ file for file in list( folder.glob( 'data/*' ) ) if path.isfile( file ) ]
data_files.sort( key=lambda x: path.getmtime( x ) )
n_frames = len( data_files ) * save_rate
get_last_file = True  # to avoid reading while python is writing
back_offset = 1 * save_rate if not get_last_file else 0

with open( data_files[ -1 ] ) as f:
    final_state = json.load( f )

previous_times = [ config[ 'model' ][ 'time_step' ] * i for i in range( n_frames - back_offset ) ]
previous_target_trajectory = target_trajectory[ :n_frames - back_offset ]
previous_actual_trajectory = array( final_state[ 'model' ][ 'previous_states' ] )[ 1:,
                             :config[ 'model' ][ 'dynamics' ][ 'state_size' ] ]
previous_actuations = array( final_state[ 'model' ][ 'previous_actuations' ] )

In [88]:
check( f'{folder}/plots' )

removing export\mpc_simulation_1747406167/plots\_angular_actuation_1747406167.png	success.
removing export\mpc_simulation_1747406167/plots\_br_0_angular_actuation_1747406167.png	success.
removing export\mpc_simulation_1747406167/plots\_br_0_linear_actuation_1747406167.png	success.
removing export\mpc_simulation_1747406167/plots\_br_0_orientation_tracking_error_1747406167.png	success.
removing export\mpc_simulation_1747406167/plots\_br_0_position_tracking_error_1747406167.png	success.
removing export\mpc_simulation_1747406167/plots\_br_1_angular_actuation_1747406167.png	success.
removing export\mpc_simulation_1747406167/plots\_br_1_linear_actuation_1747406167.png	success.
removing export\mpc_simulation_1747406167/plots\_br_1_orientation_tracking_error_1747406167.png	success.
removing export\mpc_simulation_1747406167/plots\_br_2_angular_actuation_1747406167.png	success.
removing export\mpc_simulation_1747406167/plots\_br_2_linear_actuation_1747406167.png	success.
removing export\mpc_simu

0

In [89]:
for k, v in positions.items():
    if norm( pose_weight[ v, v ] ) == 0:
        continue
    absolute_distances = abs( previous_target_trajectory[ :, v ] - previous_actual_trajectory[ :, v ] )
    plt.plot( previous_times, absolute_distances )
    plt.legend(
            [
                    r'over $\mathbf{x}_w$-axis',
                    r'over $\mathbf{y}_w$-axis',
                    r'over $\mathbf{z}_w$-axis'
            ]
    )
    plt.xlabel( 'time [s]' )
    plt.ylabel( 'absolute error [m]' )
    plt.subplots_adjust( bottom=0.125, top=1, left=0.075, right=1 )
    plt.savefig( f'{folder}/plots/{k}_tracking_error_{uuid}.png', dpi=300 )
    plt.close( 'all' )

In [90]:
for k, v in orientations.items():
    if norm( pose_weight[ v, v ] ) == 0:
        continue
    plt.plot( previous_times, abs( previous_target_trajectory[ :, v ] - previous_actual_trajectory[ :, v ] ) )
    plt.legend(
            [
                    r'around $\mathbf{x}_w$-axis',
                    r'around $\mathbf{y}_w$-axis',
                    r'around $\mathbf{z}_w$-axis'
            ]
    )
    plt.xlabel( 'time [s]' )
    plt.ylabel( 'absolute error [rad]' )
    plt.subplots_adjust( bottom=0.125, top=1, left=0.075, right=1 )
    plt.savefig( f'{folder}/plots/{k}_tracking_error_{uuid}.png', dpi=300 )
    plt.close( 'all' )

In [91]:
for k, v in linear_actuation.items():
    plt.plot( previous_times, previous_actuations[ :-1, v ] )
    plt.xlabel( 'time [s]' )
    plt.ylabel( 'actuation [N]' )
    plt.legend(
            [
                    r'over $\mathbf{x}_r$-axis',
                    r'over $\mathbf{y}_r$-axis',
                    r'over $\mathbf{z}_r$-axis'
            ]
    )
    plt.subplots_adjust( bottom=0.125, top=1, left=0.075, right=1 )
    plt.savefig( f'{folder}/plots/{k}_{uuid}.png', dpi=300 )
    plt.close( 'all' )

In [92]:
for k, v in angular_actuation.items():
    plt.plot( previous_times, previous_actuations[ :-1, v ] )
    plt.xlabel( 'time [s]' )
    plt.ylabel( 'actuation [Nm]' )
    plt.legend(
            [
                    r'around $\mathbf{x}_r$-axis',
                    r'around $\mathbf{y}_r$-axis',
                    r'around $\mathbf{z}_r$-axis'
            ]
    )
    plt.subplots_adjust( bottom=0.125, top=1, left=0.075, right=1 )
    plt.savefig( f'{folder}/plots/{k}_{uuid}.png', dpi=300 )
    plt.close( 'all' )

In [98]:
legends = [ ]
for pair_1, pair_2 in positions_pairs.items():
    key_1 = [ k for k in positions.keys() if pair_1 in k ][ 0 ]
    key_2 = [ k for k in positions.keys() if pair_2 in k ][ 0 ]
    position_1 = deepcopy( previous_actual_trajectory[ :, positions[ key_1 ] ] )
    position_2 = deepcopy( previous_actual_trajectory[ :, positions[ key_2 ] ] )

    lowest_points = zeros( (position_1.shape[ 0 ],) )
    seafloor_points = zeros( (position_1.shape[ 0 ],) )

    name = f'c_{pair_1.split( "_" )[ -1 ]}{pair_2.split( "_" )[ -1 ]}'
    cat = Catenary(
            config[ 'model' ][ 'dynamics' ][ name ][ 'length' ],
            config[ 'model' ][ 'dynamics' ][ name ][ 'linear_mass' ]
    )

    for i, (p1, p2) in enumerate( zip( position_1, position_2 ) ):
        lp = cat.get_lowest_point( p1, p2 )
        lowest_points[ i ] = lp[ 2 ]
        seafloor_points[ i ] = seafloor.get_seafloor_depth( lp )

    plt.plot( previous_times, lowest_points )
    plt.plot( previous_times, seafloor_points, ':' )
    legends += [ name, f'seafloor beneath {name}' ]

plt.legend( legends )
plt.xlabel( 'time [s]' )
plt.ylabel( 'distance [m]' )
plt.subplots_adjust( bottom=0.125, top=1, left=0.075, right=1 )
plt.gca().invert_yaxis()
plt.savefig( f'{folder}/plots/lowest_points_{uuid}.png', dpi=300 )
plt.close( 'all' )

In [99]:
for pair_1, pair_2 in positions_pairs.items():
    key_1 = [ k for k in positions.keys() if pair_1 in k ][ 0 ]
    key_2 = [ k for k in positions.keys() if pair_2 in k ][ 0 ]
    absolute_distances = norm(
            previous_actual_trajectory[ :, positions[ key_1 ] ] -
            previous_actual_trajectory[ :, positions[ key_2 ] ],
            axis=1
    )
    plt.plot( previous_times, absolute_distances )
plt.legend( [ f'from {a} to {b}' for a, b in positions_pairs.items() ] )
plt.xlabel( 'time [s]' )
plt.ylabel( 'distance [m]' )
plt.subplots_adjust( bottom=0.125, top=1, left=0.075, right=1 )
plt.savefig( f'{folder}/plots/distance_{uuid}.png', dpi=300 )
plt.close( 'all' )

In [100]:
for p1, p2 in positions_pairs.items():
    key_1 = [ k for k in positions.keys() if pair_1 in k ][ 0 ]
    key_2 = [ k for k in positions.keys() if pair_2 in k ][ 0 ]
    absolute_distances = norm(
            previous_actual_trajectory[ :, positions[ key_1 ][ :2 ] ] -
            previous_actual_trajectory[ :, positions[ key_2 ][ :2 ] ],
            axis=1
    )
    plt.plot( previous_times, absolute_distances )
plt.legend( [ f'from {a} to {b}' for a, b in positions_pairs.items() ] )
plt.xlabel( 'time [s]' )
plt.ylabel( 'distance [m]' )
plt.subplots_adjust( bottom=0.125, top=1, left=0.075, right=1 )
plt.savefig( f'{folder}/plots/horizontal_distance_{uuid}.png', dpi=300 )
plt.close( 'all' )

In [103]:
figs = [ 'x', 'y', 'z' ]

x = plt.figure().subplots()
y = plt.figure().subplots()
z = plt.figure().subplots()
z.invert_yaxis()

legends = [ [ ], [ ], [ ] ]

for k, v in positions.items():
    position = previous_actual_trajectory[ :, v ]

    X = position[ :, 0 ]
    Y = position[ :, 1 ]
    Z = position[ :, 2 ]

    x.plot( previous_times, X )
    y.plot( previous_times, Y )
    z.plot( previous_times, Z )

    for i in range( 3 ):
        legends[ i ] += [ f'{k}' ]

    if norm( pose_weight[ v, v ] ) > 0:
        target = previous_target_trajectory[ :, v ][ :, 0 ]
        x.plot( previous_times, target, ':', linewidth=3 )
        legends[ 0 ] += [ f'{k} target' ]

    if norm( pose_weight[ v, v ] ) > 0:
        target = previous_target_trajectory[ :, v ][ :, 1 ]
        y.plot( previous_times, target, ':', linewidth=3 )
        legends[ 1 ] += [ f'{k} target' ]

    if norm( pose_weight[ v, v ] ) > 0:
        target = previous_target_trajectory[ :, v ][ :, 2 ]
        z.plot( previous_times, target, ':', linewidth=3 )
        legends[ 2 ] += [ f'{k} target' ]

for f in plt.get_fignums():
    fig = plt.figure( f )
    plt.legend( legends[ f - 1 ] )
    plt.xlabel( 'time [s]' )
    plt.ylabel( f'position on $\\mathbf{{{figs[ f - 1 ]}}}_w$-axis [m]' )
    plt.subplots_adjust( bottom=0.125, top=1, left=0.075, right=1 )
    plt.savefig( f'{folder}/plots/positions_on_{figs[ f - 1 ]}_{uuid}.png', dpi=300 )
plt.close( 'all' )

In [104]:
figs = [ 'x', 'y', 'z', 'norm' ]

x = plt.figure().subplots()
y = plt.figure().subplots()
z = plt.figure().subplots()
n = plt.figure().subplots()
z.invert_yaxis()

legends = [ [ ], [ ], [ ], [ ] ]

for k, v in speeds.items():
    speed = previous_actual_trajectory[ :, v ]

    X = speed[ :, 0 ]
    Y = speed[ :, 1 ]
    Z = speed[ :, 2 ]
    N = norm( speed, axis=1 )

    x.plot( previous_times, X )
    y.plot( previous_times, Y )
    z.plot( previous_times, Z )
    n.plot( previous_times, N )

    for i in range( 4 ):
        legends[ i ] += [ f'{k}' ]

for f in plt.get_fignums():
    fig = plt.figure( f )
    plt.legend( legends[ f - 1 ] )
    plt.xlabel( 'time [s]' )
    plt.ylabel( f'speed on $\\mathbf{{{figs[ f - 1 ]}}}_r$-axis [m/s]' )
    plt.subplots_adjust( bottom=0.125, top=1, left=0.075, right=1 )
    plt.savefig( f'{folder}/plots/speeds_on_{figs[ f - 1 ]}_{uuid}.png', dpi=300 )
plt.close( 'all' )

In [106]:
plt.plot( previous_times, final_state[ 'compute_times' ] )
plt.hlines(
        config[ 'time_step' ] * config[ 'horizon' ],
        0,
        previous_times[ -1 ],
        'r',
        '--'
)
plt.legend( [ 'compute time', 'horizon depth' ] )
plt.xlabel( 'time [s]' )
plt.ylabel( 'time [s]' )
plt.subplots_adjust( bottom=0.125, top=1, left=0.075, right=1 )
plt.savefig( f'{folder}/plots/compute_times_{uuid}.png', dpi=300 )
plt.close( 'all' )

In [107]:
frames_already_done = check( f'{folder}/plots/3d_frames' )

In [111]:
robots_colors = { '0': 'r', '1': 'g', '2': 'b', '3': 'y', '4': 'm' }
quiver_scale = .5
box = [ [ -6.5, 4.5 ], [ -5.5, 5.5 ], [ -5, 6 ] ]

water_current = config[ 'model' ][ 'dynamics' ][ 'br_0' ][ 'water_current' ]
water_surface = config[ 'model' ][ 'dynamics' ][ 'br_0' ][ 'water_surface_depth' ]

Xc = linspace( box[ 0 ][ 0 ], box[ 0 ][ 1 ], 5 )
Yc = linspace( box[ 1 ][ 0 ], box[ 1 ][ 1 ], 5 )
Zc = linspace(
        box[ 2 ][ 0 ] if box[ 2 ][ 0 ] > water_surface else water_surface,
        box[ 2 ][ 1 ],
        5
)

Xc, Yc, Zc = meshgrid( Xc, Yc, Zc )

Uc = water_current[ 0 ] * ones( Xc.shape )
Vc = water_current[ 1 ] * ones( Xc.shape )
Wc = water_current[ 2 ] * ones( Xc.shape )

Xs = linspace( box[ 0 ][ 0 ], box[ 0 ][ 1 ], 1000 )
Ys = linspace( box[ 1 ][ 0 ], box[ 1 ][ 1 ], 1000 )
Xg, Yg = meshgrid( Xs, Ys )
Zws = water_surface * ones( Xg.shape )
Zsf = zeros( Xg.shape )
Zsfx = zeros( Xs.shape )
Zsfy = zeros( Ys.shape )

for i, y in enumerate( Ys ):
    Zsfy[ i ] = seafloor.get_seafloor_depth( array( [ 0, y, 0 ] ) )
    for j, x in enumerate( Xs ):
        Zsf[ i, j ] = seafloor.get_seafloor_depth( array( [ x, y, 0 ] ) )
        if i == 0:
            Zsfx[ j ] = seafloor.get_seafloor_depth( array( [ x, 0, 0 ] ) )

plot_dynamics = check( f'{folder}/data/dynamic_cable', prompt=False ) == len( positions_pairs )
dynamics = { }
if plot_dynamics:
    for bri, brj in positions_pairs.items():
        dynamics[ f'{bri}_{brj}' ] = read_csv( f'{folder}/data/dynamic_cable/{bri}_{brj}.csv' )
        # [ float( v ) for v in data[ 'x' ].strip( '[]' ).split( ',' ) ]

for frame in tqdm( range( frames_already_done, n_frames ) ):
    if frame - frames_already_done >= 50:
        raise MemoryError( 'Memory is about to be filled, erroring out to avoid computer crash' )
    with open( data_files[ int( frame / save_rate ) ] ) as f:
        simulation_state = json.load( f )
    predicted_trajectories = array( simulation_state[ 'predicted_trajectories' ] )
    if predicted_trajectories.shape[ 0 ] > 100:
        predicted_trajectories = predicted_trajectories[ ::predicted_trajectories.shape[ 0 ] // 100 ]

    fig = plt.figure( figsize=(10, 10) )
    view = plt.subplot( projection='3d', computed_zorder=False )
    view.set_xlabel( r"$\mathbf{x}_w$-axis" )
    view.set_ylabel( r"$\mathbf{y}_w$-axis" )
    view.set_zlabel( r"$\mathbf{z}_w$-axis" )
    view.set_xlim( *box[ 0 ] )
    view.set_ylim( *box[ 1 ] )
    view.set_zlim( *box[ 2 ] )
    view.invert_yaxis()
    view.invert_zaxis()

    inset_view_xz = view.inset_axes( [ .0, .0, .2, .2 ] )
    inset_view_xz.set_xlabel( r"$\mathbf{x}_w$-axis" )
    inset_view_xz.set_ylabel( r"$\mathbf{z}_w$-axis" )
    inset_view_xz.set_xlim( *box[ 0 ] )
    inset_view_xz.set_ylim( *box[ 2 ] )
    inset_view_xz.invert_yaxis()

    inset_view_yz = view.inset_axes( [ .8, .0, .2, .2 ] )
    inset_view_yz.set_xlabel( r"$\mathbf{y}_w$-axis" )
    inset_view_yz.set_ylabel( r"$\mathbf{z}_w$-axis" )
    inset_view_yz.set_xlim( *box[ 1 ] )
    inset_view_yz.set_ylim( *box[ 2 ] )
    inset_view_yz.invert_yaxis()
    inset_view_yz.invert_xaxis()

    inset_view_xy = view.inset_axes( [ .0, .8, .2, .2 ] )
    inset_view_xy.set_xlabel( r"$\mathbf{x}_w$-axis" )
    inset_view_xy.set_ylabel( r"$\mathbf{y}_w$-axis" )
    inset_view_xy.set_xlim( *box[ 0 ] )
    inset_view_xy.set_ylim( *box[ 1 ] )
    inset_view_xy.invert_yaxis()

    view.quiver( Xc, Yc, Zc, Uc, Vc, Wc, color='navy' )
    view.plot_surface( Xg, Yg, Zsf, color='brown', zorder=0. )
    view.plot_surface( Xg, Yg, Zws, color='navy', alpha=0.1 )

    inset_view_xy.pcolormesh( Xg, Yg, Zsf, cmap='RdBu' )
    inset_view_xz.plot( Xs, Zsfx, color='brown', zorder=0. )
    inset_view_yz.plot( Ys, Zsfy, color='brown', zorder=0. )
    inset_view_xz.axhline( water_surface, color='navy' )
    inset_view_yz.axhline( water_surface, color='navy' )

    for k, v in pose.items():
        color = robots_colors[ k.split( '_' )[ 2 ] ]

        if norm( pose_weight[ v, v ] ) > 0:
            Xt = target_trajectory[ :, v ][ :, 0 ]
            Yt = target_trajectory[ :, v ][ :, 1 ]
            Zt = target_trajectory[ :, v ][ :, 2 ]

            view.plot( Xt, Yt, Zt, ':', color='k' )
            view.scatter( Xt[ frame + 1 ], Yt[ frame + 1 ], Zt[ frame + 1 ], marker='x', color='k' )
            inset_view_xz.plot( Xt, Zt, ':', color='k' )
            inset_view_xz.scatter( Xt[ frame + 1 ], Zt[ frame + 1 ], marker='x', color='k' )
            inset_view_yz.plot( Yt, Zt, ':', color='k' )
            inset_view_yz.scatter( Yt[ frame + 1 ], Zt[ frame + 1 ], marker='x', color='k' )
            inset_view_xy.plot( Xt, Yt, ':', color='k' )
            inset_view_xy.scatter( Xt[ frame + 1 ], Yt[ frame + 1 ], marker='x', color='k' )

        X = previous_actual_trajectory[ frame, v ][ 0 ]
        Y = previous_actual_trajectory[ frame, v ][ 1 ]
        Z = previous_actual_trajectory[ frame, v ][ 2 ]

        P = previous_actual_trajectory[ frame, v ][ :3 ]
        A = previous_actual_trajectory[ frame, v ][ 3:6 ]
        R = Rotation.from_euler( 'xyz', A ).as_matrix()

        view.quiver( *P, *(R @ array( [ quiver_scale, 0., 0. ] )), color='r' )
        view.quiver( *P, *(R @ array( [ 0., quiver_scale, 0. ] )), color='g' )
        view.quiver( *P, *(R @ array( [ 0., 0., quiver_scale ] )), color='b' )

        view.scatter( X, Y, Z, color=color )
        inset_view_xz.scatter( X, Z, color=color )
        inset_view_yz.scatter( Y, Z, color=color )
        inset_view_xy.scatter( X, Y, color=color )

        for trajectory in predicted_trajectories:
            X = trajectory[ :, 0, v ][ :, 0 ]
            Y = trajectory[ :, 0, v ][ :, 1 ]
            Z = trajectory[ :, 0, v ][ :, 2 ]

            view.plot( X, Y, Z, linewidth=.5, color=color )
            inset_view_xz.plot( X, Z, linewidth=.5, color=color )
            inset_view_yz.plot( Y, Z, linewidth=.5, color=color )
            inset_view_xy.plot( X, Y, linewidth=.5, color=color )

    for p1, p2 in positions_pairs.items():
        color = robots_colors[ p1.split( '_' )[ 1 ] ]

        key_1 = [ k for k in positions.keys() if pair_1 in k ][ 0 ]
        key_2 = [ k for k in positions.keys() if pair_2 in k ][ 0 ]

        position_1 = deepcopy( previous_actual_trajectory[ frame, positions[ key_1 ] ] )
        position_2 = deepcopy( previous_actual_trajectory[ frame, positions[ key_2 ] ] )

        name = f'c_{p1.split( "_" )[ -1 ]}{p2.split( "_" )[ -1 ]}'
        cat = Catenary(
                config[ 'model' ][ 'dynamics' ][ name ][ 'length' ],
                config[ 'model' ][ 'dynamics' ][ name ][ 'linear_mass' ]
        )

        cat_12 = cat.discretize( position_1, position_2 )

        view.plot( cat_12[ :, 0 ], cat_12[ :, 1 ], cat_12[ :, 2 ], color=color )
        inset_view_xz.plot( cat_12[ :, 0 ], cat_12[ :, 2 ], color=color )
        inset_view_yz.plot( cat_12[ :, 1 ], cat_12[ :, 2 ], color=color )
        inset_view_xy.plot( cat_12[ :, 0 ], cat_12[ :, 1 ], color=color )

        if plot_dynamics:
            try:
                cable_12_x = [ float( v ) for v in dynamics[ f'{p1}_{p2}' ][ 'x' ][ frame ].strip( '[]' ).split( ',' ) ]
                cable_12_y = [ float( v ) for v in dynamics[ f'{p1}_{p2}' ][ 'y' ][ frame ].strip( '[]' ).split( ',' ) ]
                cable_12_z = [ -float( v ) for v in
                               dynamics[ f'{p1}_{p2}' ][ 'z' ][ frame ].strip( '[]' ).split( ',' ) ]

                view.plot( cable_12_x, cable_12_y, cable_12_z, color=color, linestyle='-.' )
                inset_view_xz.plot( cable_12_x, cable_12_z, color=color, linestyle='-.' )
                inset_view_yz.plot( cable_12_y, cable_12_z, color=color, linestyle='-.' )
                inset_view_xy.plot( cable_12_x, cable_12_y, color=color, linestyle='-.' )
            except:
                pass

    plt.savefig( f'{folder}/plots/3d_frames/{frame}.png', dpi=100 )
    plt.close( 'all' )
    del fig, view, inset_view_xz, inset_view_yz, inset_view_xy

 10%|█         | 50/500 [04:00<36:07,  4.82s/it]


MemoryError: Memory is about to be filled, erroring out to avoid computer crash

In [ ]:
collect()

In [ ]:
gif_from_pngs( f'{folder}/plots/3d_frames', duration=config[ 'model' ][ 'time_step' ] * 1000 )

In [ ]:
collect()

In [ ]:
system( f'ffmpeg -y -i {folder}/plots/3d_frames/animation.gif {folder}/plots/animation.mp4' )

In [ ]:
br_0_pose = slice_repository[ 'br_0_pose' ]
br_1_pose = slice_repository[ 'br_1_pose' ]
br_2_pose = slice_repository[ 'br_2_pose' ]
br_3_pose = slice_repository[ 'br_3_pose' ]
br_0_speed = slice_repository[ 'br_0_speed' ]
br_1_speed = slice_repository[ 'br_1_speed' ]
br_2_speed = slice_repository[ 'br_2_speed' ]
br_3_speed = slice_repository[ 'br_3_speed' ]
recorded_states = final_state[ 'model' ][ 'previous_states' ]

check( f'{folder}/data/other' )
with open( f'{folder}/data/other/robots_poses_{uuid}.csv', 'w' ) as f:
    f.write( 'br0 x, br0 y, br0 z, br0 phi, br0 theta, br0 psi, br0 u, br0 v, br0 w, br0 p, br0 q, br0 r,' )
    f.write( 'br1 x, br1 y, br1 z, br1 phi, br1 theta, br1 psi, br1 u, br1 v, br1 w, br1 p, br1 q, br1 r,' )
    f.write( 'br2 x, br2 y, br2 z, br2 phi, br2 theta, br2 psi, br2 u, br2 v, br2 w, br2 p, br2 q, br2 r,' )
    f.write( 'br3 x, br3 y, br3 z, br3 phi, br3 theta, br3 psi, br3 u, br3 v, br3 w, br3 p, br3 q, br3 r\n' )

    for state in recorded_states:
        br0 = state[ br_0_pose ] + state[ br_0_speed ]
        br1 = state[ br_1_pose ] + state[ br_1_speed ]
        br2 = state[ br_2_pose ] + state[ br_2_speed ]
        br3 = state[ br_3_pose ] + state[ br_3_speed ]

        f.write( ','.join( [ f'{v}' for v in br0 ] ) + ',' )
        f.write( ','.join( [ f'{v}' for v in br1 ] ) + ',' )
        f.write( ','.join( [ f'{v}' for v in br2 ] ) + ',' )
        f.write( ','.join( [ f'{v}' for v in br3 ] ) + '\n' )